#!/usr/bin/env bash
#:`brew commit-misc`
#:    Auto-commit everything that can be committed

# shellcheck source=../lib/funcs.sh
. "$(dirname "$0")/../lib/funcs.sh"
need_progs brew git

shopt -s lastpipe

repo=$(brew --repo homebrew/core)
timestamp=$(date +%Y%m%d.%H%M%S)

info "START: $(basename "$0")"

cd "$repo" || fatal "Can't cd into $repo"

info "Checking in aliases..."
cmd git add $(grep -l "${my_os}:" $(grep -L "fake ${my_os}" Aliases/*))
cmd git commit -m "new/updated aliases $timestamp"
