#!/usr/bin/env bash
fatal() {
  echo "FATAL ERROR: $*"
  exit 1
}

[[ -n $HOMEBREW_GITHUB_UPSTREAM ]] || fatal "HOMEBREW_GITHUB_UPSTREAM not set"
if mainbranch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null); then
  mainbranch=${mainbranch##*/}
else
  fatal "Not in Git repo"
fi
currbranch=$(git branch --show-current)
if [[ $# -eq 0 ]]; then
  git branch -a
  exit 1
fi
for b in "$@"; do
  [[ $b == $currbranch ]] && git checkout ${mainbranch}
  git push -d ${HOMEBREW_GITHUB_UPSTREAM} $b && git branch -D $b
done
git branch -a
