#!/usr/bin/env bash
#:   * refresh
#:     Interactively refreshes your Homebrew installation.
#:     This is typically used when your Brewfile lists formulae that
#:     you really want to be dependencies that can be autoremoved.
rebrew() {
    local dlist=""
    for f in "$@"; do
        dlist=$(brew deps "$f")
        if [[ -n "$dlist" ]]; then
            # shellcheck disable=SC2086
            brew rm --ignore-dependencies $dlist && brew reinstall "$f"
        fi
    done
}
declare -A processed=()
worked="-1"
until [[ $worked -eq 0 ]]; do
    worked=0
    for f in $(brew leaves); do
        [[ -n ${processed[$f]} ]] && continue
        brew info "$f"
        read -rp "Keep $f ? "
        case "${REPLY,,}" in
            y*) rebrew "$f";;
            n*) brew rm --force "$f";;
        esac
        processed["$f"]=1
        (( worked++ ))
        echo ""
    done
    brew autoremove
done
