#!/usr/bin/env bash
#:`brew url-block` *url*...
#:    Generate URL/SHA256 blocks for each *url*

# shellcheck source=../lib/funcs.sh
. "$(dirname "$0")/../lib/funcs.sh"
need_progs curl sha256sum sed

for u in "$@"; do
  cat <<EOS
    url "${u}"
    sha256 "$(curl -sL "$u" | sha256sum | sed 's/ .*//')"
EOS
done
